export const environment = {
  production:true,
  API_KEY: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjI5ZGFkM2Q4MTMzNTg2M2Q5NmQ0ZmMwZWMzYWEyYyIsInN1YiI6IjY0Zjg5ZmJhYThiMmNhMDEzODRiMjY2ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4cBZHI69PPnTqIY-N26PdMrYJ0r2APpyIyDlD7FB0yU' 
};
